'use client'

import { useState, useCallback, useEffect, useRef } from 'react'
import { 
  Palette, 
  Copy, 
  Check, 
  Contrast,
  Eye,
  Droplets,
  Shield,
  Zap
} from 'lucide-react'

interface Color {
  hex: string
  rgb: { r: number; g: number; b: number }
  hsl: { h: number; s: number; l: number }
}

interface ColorPalette {
  main: Color
  complementary: Color
  analogous: Color[]
  triadic: Color[]
  shades: Color[]
}

type ColorFormat = 'hex' | 'rgb' | 'hsl'
type ColorVision = 'normal' | 'protanopia' | 'deuteranopia' | 'tritanopia'

export default function ColorPicker() {
  const [currentColor, setCurrentColor] = useState<Color>({
    hex: '#3B82F6',
    rgb: { r: 59, g: 130, b: 246 },
    hsl: { h: 217, s: 91, l: 60 }
  })
  
  const [palette, setPalette] = useState<ColorPalette | null>(null)
  const [copiedFormat, setCopiedFormat] = useState<ColorFormat | null>(null)
  const [activeFormat, setActiveFormat] = useState<ColorFormat>('hex')
  const [colorVision, setColorVision] = useState<ColorVision>('normal')
  const [contrastColor, setContrastColor] = useState<Color>({
    hex: '#FFFFFF',
    rgb: { r: 255, g: 255, b: 255 },
    hsl: { h: 0, s: 0, l: 100 }
  })
  const [showContrast, setShowContrast] = useState(false)

  const [hue, setHue] = useState(217)
  const [saturation, setSaturation] = useState(91)
  const [lightness, setLightness] = useState(60)
  const canvasRef = useRef<HTMLCanvasElement>(null)

  // FAQ items
  const colorPickerFaqItems = [
    {
      question: "What color formats are supported?",
      answer: "We support RGB, HEX, HSL, and CMYK color formats with real-time conversion between all formats. You can input colors in any format and instantly see the equivalent values in other formats."
    },
    {
      question: "How does the color palette generator work?",
      answer: "Our palette generator creates harmonious color schemes based on color theory principles. It can generate complementary, analogous, triadic, and monochromatic palettes from your base color."
    },
    {
      question: "What is WCAG contrast ratio and why is it important?",
      answer: "WCAG (Web Content Accessibility Guidelines) contrast ratio measures the difference in luminance between text and background colors. A minimum ratio of 4.5:1 is required for normal text to ensure readability for users with visual impairments."
    },
    {
      question: "Can I simulate color blindness?",
      answer: "Yes! Our color vision simulator shows how your colors appear to people with different types of color vision deficiencies including protanopia, deuteranopia, and tritanopia."
    },
    {
      question: "Are the generated palettes copyright-free?",
      answer: "Yes, all color palettes generated by our tool are free to use for any purpose. Colors themselves cannot be copyrighted, so you can use the palettes in personal and commercial projects."
    },
    {
      question: "How accurate is the color conversion?",
      answer: "Our color conversions are mathematically precise and follow industry standards. The conversions between RGB, HEX, and HSL are exact, while CMYK conversions use standard conversion algorithms used in design software."
    }
  ]

  // Features list
  const features = [
    {
      title: 'Color Conversion',
      description: 'Convert between RGB, HEX, HSL, and CMYK color formats with real-time updates.',
      icon: Droplets
    },
    {
      title: 'Palette Generator',
      description: 'Generate beautiful color palettes with complementary, analogous, and triadic schemes.',
      icon: Palette
    },
    {
      title: 'Contrast Checker',
      description: 'Check WCAG compliance with real-time contrast ratios for accessibility.',
      icon: Contrast
    },
    {
      title: 'Vision Simulator',
      description: 'See how colors appear to users with different types of color vision deficiencies.',
      icon: Eye
    }
  ]

  // Convert HEX to RGB
  const hexToRgb = useCallback((hex: string) => {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    } : { r: 0, g: 0, b: 0 }
  }, [])

  // Convert RGB to HEX
  const rgbToHex = useCallback((r: number, g: number, b: number) => {
    return '#' + [r, g, b].map(x => {
      const hex = x.toString(16)
      return hex.length === 1 ? '0' + hex : hex
    }).join('')
  }, [])

  // Convert RGB to HSL
  const rgbToHsl = useCallback((r: number, g: number, b: number) => {
    r /= 255
    g /= 255
    b /= 255
    
    const max = Math.max(r, g, b)
    const min = Math.min(r, g, b)
    let h = 0, s = 0, l = (max + min) / 2

    if (max !== min) {
      const d = max - min
      s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
      
      switch (max) {
        case r: h = (g - b) / d + (g < b ? 6 : 0); break
        case g: h = (b - r) / d + 2; break
        case b: h = (r - g) / d + 4; break
      }
      
      h /= 6
    }

    return {
      h: Math.round(h * 360),
      s: Math.round(s * 100),
      l: Math.round(l * 100)
    }
  }, [])

  // Convert HSL to RGB
  const hslToRgb = useCallback((h: number, s: number, l: number) => {
    h /= 360
    s /= 100
    l /= 100
    
    let r, g, b

    if (s === 0) {
      r = g = b = l
    } else {
      const hue2rgb = (p: number, q: number, t: number) => {
        if (t < 0) t += 1
        if (t > 1) t -= 1
        if (t < 1/6) return p + (q - p) * 6 * t
        if (t < 1/2) return q
        if (t < 2/3) return p + (q - p) * (2/3 - t) * 6
        return p
      }
      
      const q = l < 0.5 ? l * (1 + s) : l + s - l * s
      const p = 2 * l - q
      
      r = hue2rgb(p, q, h + 1/3)
      g = hue2rgb(p, q, h)
      b = hue2rgb(p, q, h - 1/3)
    }
    
    return {
      r: Math.round(r * 255),
      g: Math.round(g * 255),
      b: Math.round(b * 255)
    }
  }, [])

  // Generate color palette
  const generatePalette = useCallback((color: Color) => {
    const { h, s, l } = color.hsl
    
    // Complementary color (opposite on color wheel)
    const compHsl = { h: (h + 180) % 360, s, l }
    const compRgb = hslToRgb(compHsl.h, compHsl.s, compHsl.l)
    const complementary = {
      hex: rgbToHex(compRgb.r, compRgb.g, compRgb.b),
      rgb: compRgb,
      hsl: compHsl
    }

    // Analogous colors (30° apart)
    const analogous = [
      { h: (h + 30) % 360, s, l },
      { h: (h - 30 + 360) % 360, s, l }
    ].map(hsl => {
      const rgb = hslToRgb(hsl.h, hsl.s, hsl.l)
      return {
        hex: rgbToHex(rgb.r, rgb.g, rgb.b),
        rgb,
        hsl
      }
    })

    // Triadic colors (120° apart)
    const triadic = [
      { h: (h + 120) % 360, s, l },
      { h: (h + 240) % 360, s, l }
    ].map(hsl => {
      const rgb = hslToRgb(hsl.h, hsl.s, hsl.l)
      return {
        hex: rgbToHex(rgb.r, rgb.g, rgb.b),
        rgb,
        hsl
      }
    })

    // Shades (different lightness levels)
    const shades = [20, 40, 60, 80].map(lightness => {
      const hsl = { h, s, l: lightness }
      const rgb = hslToRgb(hsl.h, hsl.s, hsl.l)
      return {
        hex: rgbToHex(rgb.r, rgb.g, rgb.b),
        rgb,
        hsl
      }
    })

    setPalette({
      main: color,
      complementary,
      analogous,
      triadic,
      shades
    })
  }, [hslToRgb, rgbToHex])

  // Update color from HEX input
  const updateColorFromHex = useCallback((hex: string) => {
    const rgb = hexToRgb(hex)
    const hsl = rgbToHsl(rgb.r, rgb.g, rgb.b)
    const newColor = { hex, rgb, hsl }
    setCurrentColor(newColor)
    setHue(hsl.h)
    setSaturation(hsl.s)
    setLightness(hsl.l)
    generatePalette(newColor)
  }, [hexToRgb, rgbToHsl, generatePalette])

  // Update color from RGB input
  const updateColorFromRgb = useCallback((r: number, g: number, b: number) => {
    const hex = rgbToHex(r, g, b)
    const hsl = rgbToHsl(r, g, b)
    const newColor = { hex, rgb: { r, g, b }, hsl }
    setCurrentColor(newColor)
    setHue(hsl.h)
    setSaturation(hsl.s)
    setLightness(hsl.l)
    generatePalette(newColor)
  }, [rgbToHex, rgbToHsl, generatePalette])

  // Update color from HSL input
  const updateColorFromHsl = useCallback((h: number, s: number, l: number) => {
    const rgb = hslToRgb(h, s, l)
    const hex = rgbToHex(rgb.r, rgb.g, rgb.b)
    const newColor = { hex, rgb, hsl: { h, s, l } }
    setCurrentColor(newColor)
    setHue(h)
    setSaturation(s)
    setLightness(l)
    generatePalette(newColor)
  }, [hslToRgb, rgbToHex, generatePalette])

  // Copy color to clipboard
  const copyToClipboard = useCallback((text: string, format: ColorFormat) => {
    navigator.clipboard.writeText(text)
    setCopiedFormat(format)
    setTimeout(() => setCopiedFormat(null), 2000)
  }, [])

  // Calculate contrast ratio
  const calculateContrast = useCallback((color1: Color, color2: Color) => {
    const getLuminance = (r: number, g: number, b: number) => {
      const [rs, gs, bs] = [r, g, b].map(c => {
        c = c / 255
        return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)
      })
      return 0.2126 * rs + 0.7152 * gs + 0.0722 * bs
    }
    
    const l1 = getLuminance(color1.rgb.r, color1.rgb.g, color1.rgb.b)
    const l2 = getLuminance(color2.rgb.r, color2.rgb.g, color2.rgb.b)
    const contrast = (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05)
    
    return contrast.toFixed(2)
  }, [])

  // Get WCAG rating
  const getWcagRating = useCallback((contrast: number) => {
    if (contrast >= 7) return { rating: 'AAA', color: 'text-green-600' }
    if (contrast >= 4.5) return { rating: 'AA', color: 'text-emerald-600' }
    if (contrast >= 3) return { rating: 'AA Large', color: 'text-yellow-600' }
    return { rating: 'Fail', color: 'text-red-600' }
  }, [])

  // Simulate color vision deficiency
  const simulateColorVision = useCallback((color: Color, vision: ColorVision): Color => {
    const { r, g, b } = color.rgb
    
    // Color vision deficiency matrices
    const matrices = {
      normal: [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
      protanopia: [[0.567, 0.433, 0], [0.558, 0.442, 0], [0, 0.242, 0.758]],
      deuteranopia: [[0.625, 0.375, 0], [0.7, 0.3, 0], [0, 0.3, 0.7]],
      tritanopia: [[0.95, 0.05, 0], [0, 0.433, 0.567], [0, 0.475, 0.525]]
    }
    
    const matrix = matrices[vision]
    const newR = r * matrix[0][0] + g * matrix[0][1] + b * matrix[0][2]
    const newG = r * matrix[1][0] + g * matrix[1][1] + b * matrix[1][2]
    const newB = r * matrix[2][0] + g * matrix[2][1] + b * matrix[2][2]
    
    const newHex = rgbToHex(Math.round(newR), Math.round(newG), Math.round(newB))
    const newRgb = { r: Math.round(newR), g: Math.round(newG), b: Math.round(newB) }
    const newHsl = rgbToHsl(newRgb.r, newRgb.g, newRgb.b)
    
    return { hex: newHex, rgb: newRgb, hsl: newHsl }
  }, [rgbToHex, rgbToHsl])

  // Initialize canvas
  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return

    const ctx = canvas.getContext('2d')
    if (!ctx) return

    const width = canvas.width
    const height = canvas.height

    // Create hue gradient (left to right)
    const hueGradient = ctx.createLinearGradient(0, 0, width, 0)
    for (let i = 0; i <= 360; i += 60) {
      const rgb = hslToRgb(i, 100, 50)
      hueGradient.addColorStop(i / 360, `rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`)
    }
    
    // Create saturation/lightness gradient (top to bottom)
    const slGradient = ctx.createLinearGradient(0, 0, 0, height)
    slGradient.addColorStop(0, 'rgba(255,255,255,1)')
    slGradient.addColorStop(0.5, 'rgba(255,255,255,0)')
    slGradient.addColorStop(1, 'rgba(0,0,0,1)')

    // Fill with base hue
    ctx.fillStyle = hueGradient
    ctx.fillRect(0, 0, width, height)

    // Apply saturation/lightness overlay
    ctx.fillStyle = slGradient
    ctx.fillRect(0, 0, width, height)
  }, [hslToRgb])

  // Update color from canvas click
  const handleCanvasClick = useCallback((event: React.MouseEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current
    if (!canvas) return

    const rect = canvas.getBoundingClientRect()
    const x = event.clientX - rect.left
    const y = event.clientY - rect.top
    
    // Use the actual rendered dimensions, not the canvas element dimensions
    const renderedWidth = rect.width
    const renderedHeight = rect.height
    
    // Calculate normalized coordinates (0-1)
    const normalizedX = Math.max(0, Math.min(1, x / renderedWidth))
    const normalizedY = Math.max(0, Math.min(1, y / renderedHeight))
    
    // Calculate hue from x position (0-360)
    const newHue = normalizedX * 360
    
    // Calculate saturation and lightness from y position
    const newSaturation = 100 - (normalizedY * 100)
    const newLightness = normalizedY * 100
    
    setHue(newHue)
    setSaturation(newSaturation)
    setLightness(newLightness)
    
    // Update the current color
    const rgb = hslToRgb(newHue, newSaturation, newLightness)
    const hex = rgbToHex(rgb.r, rgb.g, rgb.b)
    const newColor = { 
      hex, 
      rgb, 
      hsl: { h: newHue, s: newSaturation, l: newLightness } 
    }
    
    setCurrentColor(newColor)
    generatePalette(newColor)
  }, [hslToRgb, rgbToHex, generatePalette])

  // Initialize and redraw canvas on resize
  const drawCanvas = useCallback(() => {
    const canvas = canvasRef.current
    if (!canvas) return

    const ctx = canvas.getContext('2d')
    if (!ctx) return

    // Use the actual rendered size, not the element size
    const rect = canvas.getBoundingClientRect()
    canvas.width = rect.width
    canvas.height = rect.height

    const width = canvas.width
    const height = canvas.height

    // Clear canvas
    ctx.clearRect(0, 0, width, height)

    // Create hue gradient (left to right)
    const hueGradient = ctx.createLinearGradient(0, 0, width, 0)
    hueGradient.addColorStop(0, '#ff0000') // Red
    hueGradient.addColorStop(0.17, '#ffff00') // Yellow
    hueGradient.addColorStop(0.33, '#00ff00') // Green
    hueGradient.addColorStop(0.5, '#00ffff') // Cyan
    hueGradient.addColorStop(0.67, '#0000ff') // Blue
    hueGradient.addColorStop(0.83, '#ff00ff') // Magenta
    hueGradient.addColorStop(1, '#ff0000') // Back to Red

    // Create saturation/lightness gradient (top to bottom)
    const slGradient = ctx.createLinearGradient(0, 0, 0, height)
    slGradient.addColorStop(0, 'rgba(255,255,255,1)')
    slGradient.addColorStop(0.5, 'rgba(255,255,255,0)')
    slGradient.addColorStop(1, 'rgba(0,0,0,1)')

    // Fill with base hue
    ctx.fillStyle = hueGradient
    ctx.fillRect(0, 0, width, height)

    // Apply saturation/lightness overlay
    ctx.fillStyle = slGradient
    ctx.fillRect(0, 0, width, height)
  }, [])

  // Redraw canvas on mount and resize
  useEffect(() => {
    drawCanvas()
    
    const handleResize = () => {
      drawCanvas()
    }

    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [drawCanvas])

  // Update color from hue slider
  const handleHueChange = useCallback((newHue: number) => {
    setHue(newHue)
    const rgb = hslToRgb(newHue, saturation, lightness)
    const hex = rgbToHex(rgb.r, rgb.g, rgb.b)
    const newColor = { 
      hex, 
      rgb, 
      hsl: { h: newHue, s: saturation, l: lightness } 
    }
    setCurrentColor(newColor)
    generatePalette(newColor)
  }, [saturation, lightness, hslToRgb, rgbToHex, generatePalette])

  // Update color from saturation/lightness
  const updateFromSL = useCallback((newSaturation: number, newLightness: number) => {
    setSaturation(newSaturation)
    setLightness(newLightness)
    const rgb = hslToRgb(hue, newSaturation, newLightness)
    const hex = rgbToHex(rgb.r, rgb.g, rgb.b)
    const newColor = { 
      hex, 
      rgb, 
      hsl: { h: hue, s: newSaturation, l: newLightness } 
    }
    setCurrentColor(newColor)
    generatePalette(newColor)
  }, [hue, hslToRgb, rgbToHex, generatePalette])

  // Initialize palette
  useEffect(() => {
    generatePalette(currentColor)
  }, [currentColor, generatePalette])

  const contrastRatio = calculateContrast(currentColor, contrastColor)
  const wcagRating = getWcagRating(parseFloat(contrastRatio))
  const simulatedColor = simulateColorVision(currentColor, colorVision)

  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-teal-50 to-cyan-50 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Main Header */}
        <header className="text-center mb-12">
          <div className="inline-flex items-center justify-center p-3 bg-gradient-to-r from-green-500 to-emerald-500 rounded-2xl shadow-lg mb-4">
            <Palette className="h-8 w-8 text-white" />
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Advanced Color Picker
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Professional color tools with real-time conversion, palette generation, 
            contrast checking, and accessibility features for designers and developers.
          </p>
        </header>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Main Color Picker */}
          <div className="lg:col-span-2 space-y-6">
            {/* Interactive Color Canvas */}
            <div className="bg-white rounded-2xl shadow-xl border border-emerald-100 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Color Canvas</h3>
              
              {/* Main Color Picker Area */}
              <div className="relative mb-4">
                <div className="relative w-full h-64 rounded-xl border border-gray-200 overflow-hidden">
                  <canvas
                    ref={canvasRef}
                    onClick={handleCanvasClick}
                    className="absolute inset-0 w-full h-full cursor-crosshair"
                  />
                  {/* Selection indicator */}
                  <div
                    className="absolute w-4 h-4 border-2 border-white rounded-full shadow-lg pointer-events-none transform -translate-x-2 -translate-y-2"
                    style={{
                      left: `${(hue / 360) * 100}%`,
                      top: `${(100 - saturation)}%`,
                    }}
                  />
                </div>
              </div>

              {/* Hue Slider */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Hue: {Math.round(hue)}°
                </label>
                <div className="relative">
                  <input
                    type="range"
                    min="0"
                    max="360"
                    value={hue}
                    onChange={(e) => handleHueChange(parseInt(e.target.value))}
                    className="w-full h-3 bg-gradient-to-r from-red-500 via-yellow-500 via-green-500 via-blue-500 via-indigo-500 via-violet-500 to-red-500 rounded-lg appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white [&::-webkit-slider-thumb]:border-2 [&::-webkit-slider-thumb]:border-gray-400"
                  />
                </div>
              </div>

              {/* Saturation and Lightness Sliders */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Saturation: {Math.round(saturation)}%
                  </label>
                  <input
                    type="range"
                    min="0"
                    max="100"
                    value={saturation}
                    onChange={(e) => updateFromSL(parseInt(e.target.value), lightness)}
                    className="w-full h-2 bg-gradient-to-r from-gray-300 to-current rounded-lg appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white [&::-webkit-slider-thumb]:border-2 [&::-webkit-slider-thumb]:border-gray-400"
                    style={{ '--tw-gradient-to': currentColor.hex } as any}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Lightness: {Math.round(lightness)}%
                  </label>
                  <input
                    type="range"
                    min="0"
                    max="100"
                    value={lightness}
                    onChange={(e) => updateFromSL(saturation, parseInt(e.target.value))}
                    className="w-full h-2 bg-gradient-to-r from-black via-current to-white rounded-lg appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white [&::-webkit-slider-thumb]:border-2 [&::-webkit-slider-thumb]:border-gray-400"
                    style={{ '--tw-gradient-to': currentColor.hex } as any}
                  />
                </div>
              </div>

              {/* Current Color Display */}
              <div className="mt-4 p-4 rounded-lg border border-gray-200 bg-gray-50">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-4">
                    <div 
                      className="w-16 h-16 rounded-lg border border-gray-200 shadow-sm"
                      style={{ backgroundColor: currentColor.hex }}
                    />
                    <div>
                      <div className="font-mono text-lg font-semibold text-gray-900">
                        {currentColor.hex}
                      </div>
                      <div className="text-sm text-gray-600">
                        RGB({currentColor.rgb.r}, {currentColor.rgb.g}, {currentColor.rgb.b})
                      </div>
                      <div className="text-sm text-gray-600">
                        HSL({Math.round(currentColor.hsl.h)}°, {Math.round(currentColor.hsl.s)}%, {Math.round(currentColor.hsl.l)}%)
                      </div>
                    </div>
                  </div>
                  <button
                    onClick={() => copyToClipboard(currentColor.hex, 'hex')}
                    className="p-2 text-gray-400 hover:text-emerald-600 transition-colors"
                    title="Copy color"
                  >
                    {copiedFormat === 'hex' ? <Check className="h-5 w-5" /> : <Copy className="h-5 w-5" />}
                  </button>
                </div>
              </div>
            </div>

            {/* Color Format Inputs */}
            <div className="bg-white rounded-2xl shadow-xl border border-emerald-100 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Color Values</h3>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">HEX</label>
                  <div className="relative">
                    <input
                      type="text"
                      value={currentColor.hex}
                      onChange={(e) => updateColorFromHex(e.target.value)}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2 font-mono focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                    <button
                      onClick={() => copyToClipboard(currentColor.hex, 'hex')}
                      className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-emerald-600"
                    >
                      {copiedFormat === 'hex' ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                    </button>
                  </div>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">RGB</label>
                  <div className="relative">
                    <input
                      type="text"
                      value={`${currentColor.rgb.r}, ${currentColor.rgb.g}, ${currentColor.rgb.b}`}
                      onChange={(e) => {
                        const [r, g, b] = e.target.value.split(',').map(x => parseInt(x.trim()) || 0)
                        updateColorFromRgb(r, g, b)
                      }}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2 font-mono focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                    <button
                      onClick={() => copyToClipboard(`rgb(${currentColor.rgb.r}, ${currentColor.rgb.g}, ${currentColor.rgb.b})`, 'rgb')}
                      className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-emerald-600"
                    >
                      {copiedFormat === 'rgb' ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                    </button>
                  </div>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">HSL</label>
                  <div className="relative">
                    <input
                      type="text"
                      value={`${Math.round(currentColor.hsl.h)}, ${Math.round(currentColor.hsl.s)}%, ${Math.round(currentColor.hsl.l)}%`}
                      onChange={(e) => {
                        const [h, s, l] = e.target.value.split(',').map(x => parseInt(x.trim()) || 0)
                        updateColorFromHsl(h, s, l)
                      }}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2 font-mono focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                    <button
                      onClick={() => copyToClipboard(`hsl(${Math.round(currentColor.hsl.h)}, ${Math.round(currentColor.hsl.s)}%, ${Math.round(currentColor.hsl.l)}%)`, 'hsl')}
                      className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-emerald-600"
                    >
                      {copiedFormat === 'hsl' ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Color Palette */}
            {palette && (
              <div className="bg-white rounded-2xl shadow-xl border border-emerald-100 p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Color Palette</h3>
                
                <div className="space-y-4">
                  {/* Main & Complementary */}
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 mb-2">Main Color</h4>
                      <div className="flex items-center space-x-3">
                        <div 
                          className="w-12 h-12 rounded-lg border border-gray-200 shadow-sm"
                          style={{ backgroundColor: palette.main.hex }}
                        />
                        <div className="font-mono text-sm">{palette.main.hex}</div>
                      </div>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-700 mb-2">Complementary</h4>
                      <div className="flex items-center space-x-3">
                        <div 
                          className="w-12 h-12 rounded-lg border border-gray-200 shadow-sm"
                          style={{ backgroundColor: palette.complementary.hex }}
                        />
                        <div className="font-mono text-sm">{palette.complementary.hex}</div>
                      </div>
                    </div>
                  </div>

                  {/* Analogous Colors */}
                  <div>
                    <h4 className="text-sm font-medium text-gray-700 mb-2">Analogous Colors</h4>
                    <div className="grid grid-cols-2 gap-3">
                      {palette.analogous.map((color, index) => (
                        <div key={index} className="flex items-center space-x-3">
                          <div 
                            className="w-10 h-10 rounded-lg border border-gray-200 shadow-sm"
                            style={{ backgroundColor: color.hex }}
                          />
                          <div className="font-mono text-sm">{color.hex}</div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Shades */}
                  <div>
                    <h4 className="text-sm font-medium text-gray-700 mb-2">Shades</h4>
                    <div className="grid grid-cols-4 gap-2">
                      {palette.shades.map((color, index) => (
                        <div key={index} className="text-center">
                          <div 
                            className="w-full h-8 rounded-lg border border-gray-200 shadow-sm mb-1"
                            style={{ backgroundColor: color.hex }}
                          />
                          <div className="font-mono text-xs">{color.hex}</div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Tools Panel */}
          <div className="space-y-6">
            {/* Security Features */}
            <div className="bg-white rounded-xl p-6 shadow-lg border border-emerald-100">
              <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <Shield className="h-5 w-5 text-emerald-500 mr-2" />
                Security Features
              </h3>
              <ul className="space-y-3 text-sm text-gray-600">
                <li className="flex items-start space-x-2">
                  <Zap className="h-4 w-4 text-emerald-500 mt-0.5 flex-shrink-0" />
                  <span><strong>Client-Side Processing</strong> - All color processing happens in your browser</span>
                </li>
                <li className="flex items-start space-x-2">
                  <Shield className="h-4 w-4 text-emerald-500 mt-0.5 flex-shrink-0" />
                  <span><strong>No Data Stored</strong> - Your color choices never leave your device</span>
                </li>
                <li className="flex items-start space-x-2">
                  <Palette className="h-4 w-4 text-emerald-500 mt-0.5 flex-shrink-0" />
                  <span><strong>Instant Conversion</strong> - Real-time color format conversion</span>
                </li>
              </ul>
            </div>

            {/* Format Selector */}
            <div className="bg-white rounded-2xl shadow-xl border border-emerald-100 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Color Format</h3>
              <div className="grid grid-cols-3 gap-2">
                {(['hex', 'rgb', 'hsl'] as ColorFormat[]).map((format) => (
                  <button
                    key={format}
                    onClick={() => setActiveFormat(format)}
                    className={`px-3 py-2 rounded-lg font-medium text-sm transition-colors ${
                      activeFormat === format
                        ? 'bg-emerald-500 text-white'
                        : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                    }`}
                  >
                    {format.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>

            {/* Contrast Checker */}
            <div className="bg-white rounded-2xl shadow-xl border border-emerald-100 p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-gray-900">Contrast Checker</h3>
                <button
                  onClick={() => setShowContrast(!showContrast)}
                  className="p-1 text-gray-400 hover:text-emerald-600"
                >
                  <Contrast className="h-5 w-5" />
                </button>
              </div>
              
              {showContrast && (
                <div className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">Foreground</label>
                      <input
                        type="color"
                        value={currentColor.hex}
                        onChange={(e) => updateColorFromHex(e.target.value)}
                        className="w-full h-10 rounded-lg border border-gray-300"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">Background</label>
                      <input
                        type="color"
                        value={contrastColor.hex}
                        onChange={(e) => {
                          const rgb = hexToRgb(e.target.value)
                          const hsl = rgbToHsl(rgb.r, rgb.g, rgb.b)
                          setContrastColor({ hex: e.target.value, rgb, hsl })
                        }}
                        className="w-full h-10 rounded-lg border border-gray-300"
                      />
                    </div>
                  </div>
                  
                  <div className="p-4 rounded-lg border border-gray-200 text-center">
                    <div className="text-2xl font-bold text-gray-900">{contrastRatio}:1</div>
                    <div className={`text-sm font-medium ${wcagRating.color}`}>
                      WCAG {wcagRating.rating}
                    </div>
                  </div>
                  
                  <div 
                    className="p-4 rounded-lg text-center font-semibold"
                    style={{ 
                      backgroundColor: contrastColor.hex,
                      color: currentColor.hex
                    }}
                  >
                    Sample Text
                  </div>
                </div>
              )}
            </div>

            {/* Color Vision Simulator */}
            <div className="bg-white rounded-2xl shadow-xl border border-emerald-100 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Vision Simulator</h3>
              <div className="space-y-3">
                {(['normal', 'protanopia', 'deuteranopia', 'tritanopia'] as ColorVision[]).map((vision) => (
                  <button
                    key={vision}
                    onClick={() => setColorVision(vision)}
                    className={`w-full px-4 py-3 rounded-lg text-left transition-colors ${
                      colorVision === vision
                        ? 'bg-emerald-500 text-white'
                        : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="capitalize">{vision}</span>
                      <div 
                        className="w-6 h-6 rounded border border-gray-300"
                        style={{ backgroundColor: simulateColorVision(currentColor, vision).hex }}
                      />
                    </div>
                  </button>
                ))}
              </div>
              
              <div className="mt-4 p-4 rounded-lg border border-gray-200 text-center">
                <div 
                  className="w-full h-16 rounded-lg mb-2 border border-gray-200"
                  style={{ backgroundColor: simulatedColor.hex }}
                />
                <div className="font-mono text-sm text-gray-600">
                  {simulatedColor.hex}
                </div>
              </div>
            </div>

            {/* Quick Colors */}
            <div className="bg-white rounded-2xl shadow-xl border border-emerald-100 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Quick Colors</h3>
              <div className="grid grid-cols-4 gap-2">
                {[
                  '#3B82F6', '#EF4444', '#10B981', '#F59E0B',
                  '#8B5CF6', '#EC4899', '#06B6D4', '#84CC16',
                  '#F97316', '#6366F1', '#14B8A6', '#EAB308'
                ].map((color) => (
                  <button
                    key={color}
                    onClick={() => updateColorFromHex(color)}
                    className="w-8 h-8 rounded-lg border border-gray-200 shadow-sm hover:scale-110 transition-transform"
                    style={{ backgroundColor: color }}
                    title={color}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Features Section */}
        <div className="max-w-6xl mx-auto mt-16">
          <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">
            Color Tools & Features
          </h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, index) => (
              <div key={index} className="bg-white rounded-xl p-6 shadow-lg border border-gray-200 hover:shadow-xl transition-shadow">
                <div className="inline-flex items-center justify-center w-12 h-12 bg-gradient-to-r from-green-500 to-emerald-500 rounded-xl mb-4">
                  <feature.icon className="h-6 w-6 text-white" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">{feature.title}</h3>
                <p className="text-gray-600 text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* FAQ Section */}
        <div className="mt-16">
          <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">
            Frequently Asked Questions
          </h2>
          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {colorPickerFaqItems.map((faq, index) => (
              <div key={index} className="bg-white rounded-xl p-6 shadow-lg border border-emerald-100">
                <h3 className="text-lg font-semibold text-gray-900 mb-3">{faq.question}</h3>
                <p className="text-gray-600 text-sm leading-relaxed">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>

        {/* SEO Content */}
        <div className="max-w-4xl mx-auto mt-12 prose prose-lg">
          <h2 className="text-3xl font-bold text-gray-900 mb-6">
            Advanced Color Picker & Design Tools
          </h2>
          
          <p className="text-gray-700 mb-4">
            Our comprehensive color picker provides professional-grade tools for designers and developers. 
            Convert between color formats, generate harmonious palettes, check accessibility compliance, 
            and ensure your colors work for all users with our color vision simulation.
          </p>

          <h3 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
            Professional Color Management
          </h3>
          <p className="text-gray-700 mb-4">
            Work with precision using real-time color conversion between HEX, RGB, and HSL formats. 
            Our mathematically accurate algorithms ensure consistent results across all your design projects.
          </p>

          <h3 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
            Accessibility-First Design
          </h3>
          <p className="text-gray-700 mb-4">
            Build inclusive designs with our WCAG contrast checker and color vision deficiency simulator. 
            Ensure your color choices meet accessibility standards and work for users with different types 
            of color vision.
          </p>

          <h3 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
            Smart Color Palettes
          </h3>
          <p className="text-gray-700 mb-4">
            Generate beautiful, harmonious color schemes based on color theory principles. Create complementary, 
            analogous, and triadic palettes that work perfectly together for your design systems and branding.
          </p>
        </div>
      </div>

      {/* FAQ Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": colorPickerFaqItems.map(faq => ({
              "@type": "Question",
              "name": faq.question,
              "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
              }
            }))
          })
        }}
      />
    </div>
  )
}